extends:
    - stylelint-config-recommended-scss
    - stylelint-config-property-sort-order-smacss
    - stylelint-config-sass-guidelines
plugins:
    - stylelint-scss
rules:
    max-nesting-depth: null
    selector-max-compound-selectors: null
    selector-class-pattern: null
    scss/dollar-variable-pattern: null
    no-empty-source: null
    selector-pseudo-element-no-unknown: null
    scss/no-global-function-names: null
    order/properties-order: null
    function-parentheses-space-inside: null
